function d = get_resampled_mpc_data(dat, starts, duration, order)
    % M. Sinner 1/2/20

    d(2).time = 0;
    for i = 1:2
        d(i).time = dat.time(round(starts(order(i))*100):...
                             round((starts(order(i))+duration)*100));
        d(i).pitch = dat.pitch_command(round(starts(order(i))*100):...
                                      round((starts(order(i))+...
                                                    duration)*100));
        d(i).speed = dat.rpm(round(starts(order(i))*100):...
                             round((starts(order(i))+duration)*100));
        d(i).fbonly = dat.feedback_only(round(starts(order(i))*100):...
                                        round((starts(order(i))+...
                                                      duration)*100));
    end

    d(2).HW = dat.HW_wind_speed(round(starts(2)*100):...
                                round((starts(2)+duration)*100));
end

