function c = get_mpc_computation_performance(dat, starts, duration, order)
    % M. Sinner 1/2/20

    c(2).time = 0;
    for i = 1:2
        c(i).time = dat.time(round(starts(order(i))*100):...
                             round((starts(order(i))+duration)*100));
        c(i).solve_status = dat.solve_status(round(starts(order(i))*...
                                                          100):...
                                             round((starts(order(i))+...
                                                          duration)*100));
        c(i).t_solve_ms = dat.solve_time_ms(round(starts(order(i))*100):...
                                  round((starts(order(i))+duration)*100));
        
        c(i).nWSR = dat.iterations(round(starts(order(i))*100):...
                                   round((starts(order(i))+duration)*100));
        
        c(i).fbonly = dat.feedback_only(round(starts(order(i))*100):...
                                        round((starts(order(i))+...
                                                      duration)*100));
    end
end

